"""empty message

Revision ID: 537aa28ff31f
Revises: 
Create Date: 2025-05-19 18:07:28.890618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '537aa28ff31f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HouseModel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('GrLivArea', sa.Integer(), nullable=False),
    sa.Column('YearBuilt', sa.Integer(), nullable=False),
    sa.Column('GarageCars', sa.Integer(), nullable=False),
    sa.Column('TotalBsmtSF', sa.Integer(), nullable=False),
    sa.Column('FullBath', sa.Integer(), nullable=False),
    sa.Column('OverallQual', sa.Integer(), nullable=False),
    sa.Column('Neighborhood', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fio', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('date_registered', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('RefreshToken',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RefreshToken')
    op.drop_table('users')
    op.drop_table('HouseModel')
    # ### end Alembic commands ###
