"""empty message

Revision ID: 9f08805a4ccf
Revises: 537aa28ff31f
Create Date: 2025-05-25 00:29:22.811571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f08805a4ccf'
down_revision: Union[str, None] = '537aa28ff31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('HouseModel', sa.Column('price', sa.Integer(), nullable=True))
    op.alter_column('HouseModel', 'Neighborhood',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('HouseModel', 'Neighborhood',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('HouseModel', 'price')
    # ### end Alembic commands ###
